groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: tfstate
  type: s3
  source:
    bucket: gcp-concourse
    endpoint: {{minio_endpoint}}
    regexp: "terraform/terraform-(.*).tfstate"
    access_key_id: {{minio_access_key_id}}
    secret_access_key: {{minio_secret_access_key}}

- name: tfstate-version
  type: semver
  source:
   driver: s3
   bucket: gcp-concourse
   key: terraform/version
   access_key_id: {{minio_access_key_id}}
   secret_access_key: {{minio_secret_access_key}}
   endpoint: {{minio_endpoint}}
   initial_version: 0.0.0
   region_name: us-east-1

- name: gcp-concourse
  type: git
  source:
    uri: https://github.com/krishicks/gcp-concourse.git
    branch: master

- name: ert-concourse
  type: git
  source:
    uri: https://github.com/c0-ops/ert-concourse.git
    branch: master

- name: pivnet-opsmgr
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

jobs:
- name: wipe-env
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: gcp-concourse
    - get: tfstate
    - get: tfstate-version
      params:
        bump: major
  - task: wipe
    file: gcp-concourse/tasks/wipe-env.yml
    params:
      GOOGLE_PROJECT: {{gcp_project_id}}
      GOOGLE_REGION: {{gcp_region}}
      GOOGLE_CREDENTIALS: {{gcp_service_account_key}}
  - put: tfstate
    params:
      file: wipe-output/*.tfstate
  - put: tfstate-version
    params:
      file: tfstate-version/version

- name: upload-opsman-image
  plan:
  - get: gcp-concourse
  - get: pivnet-opsmgr
    params:
      globs:
      - "*GCP.yml"
  - task: upload
    file: gcp-concourse/tasks/upload-opsman.yml
    params:
      GOOGLE_PROJECT: {{gcp_project_id}}
      GOOGLE_REGION: {{gcp_region}}
      GOOGLE_CREDENTIALS: {{gcp_service_account_key}}

- name: create-infrastructure
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: ert-concourse
    - get: gcp-concourse
      passed: [upload-opsman-image]
    - get: pivnet-opsmgr
      passed: [upload-opsman-image]
      params:
        globs:
        - "*GCP.yml"
    - get: tfstate-version
      params:
        bump: major
  - task: create-infrastructure
    file: gcp-concourse/tasks/create-infrastructure.yml
    params:
      GOOGLE_PROJECT: {{gcp_project_id}}
      GOOGLE_REGION: {{gcp_region}}
      GOOGLE_CREDENTIALS: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      RESOURCE_PREFIX: {{gcp_prefix}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      PCF_ERT_SSL_CERT: {{pcf_ert_ssl_cert}}
      PCF_ERT_SSL_KEY: {{pcf_ert_ssl_key}}
      ERT_SQL_DB_USERNAME: {{ert_sql_db_username}}
      ERT_SQL_DB_PASSWORD: {{ert_sql_db_password}}
  - put: tfstate
    params:
      file: create-infrastructure-output/*.tfstate
  - put: tfstate-version
    params:
      file: tfstate-version/version
