---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: gcp-concourse
- name: tfstate
- name: tfstate-version

outputs:
- name: wipe-output

params:
  GOOGLE_PROJECT:
  GOOGLE_REGION:
  GOOGLE_SERVICE_ACCOUNT_KEY:

run:
  path: gcp-concourse/tasks/wipe-env.sh
